apiVersion: v1
kind: Secret
metadata: 
  name: db-secret
  namespace: exam
type: Opaque
data:
  mysql-user-password:  dEBzdEByMkA=
  mysql-root-password:  cEBzc3dAcmRyQEB0==

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configMap
  namespace: exam
data:
  username: "tester"
  db-name: "exdb"

---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: exam
spec:
  selector:
    app: mysql
  ports :
    - protocol : TCP
      port : 3306
      targetPort: 3306

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
  namespace: exam
spec:
  serviceName: db-service
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: MySQL-database
        image: mysql:9.1.0-oracle
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: mysql-root-password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: db-configMap
                key: db-name
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: db-configMap
                key: username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: mysql-user-password
        ports:
          - containerPort: 3306
            name: db-port
        volumeMounts:
          - name: storageVol
            mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: storageVol
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

