apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-rbac
  namespace: exam
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["gets", "list", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-rbac
  namespace: exam
subjects:
  - kind: User
    name: user1
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: role-rbac
  apiGroup: rbac.authorization.k8s.io
  